//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Draw.rc
//
#define IDR_DRAWTYPE_SRVR_IP            4
#define IDR_DRAWTYPE_SRVR_EMB           5
#define IDR_DRAWTYPE_CNTR_IP            6
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDW_TOOLBOX_BAR                 101
#define IDP_FAILED_TO_CREATE            102
#define ID_LINESTYLE                    102
#define ID_CANCEL_EDIT                  103
#define IDR_MAINFRAME                   128
#define IDR_DRAWTYPE                    129
#define IDB_IMGLIST_TAB                 130
#define IDB_IMGLIST_VIEW                131
#define IDD_SUMM_PAGE                   140
#define IDD_STAT_PAGE                   141
#define IDR_TOOLBAR_BOX                 142
#define IDR_FORMATTING                  144
#define IDR_BORDERS                     146
#define IDR_LINE_WIDTH                  151
#define ID_POPUP_MENU                   153
#define IDC_PENCIL                      154
#define IDD_PROP_RECT                   155
#define IDB_ARROWS                      157
#define IDD_FILL_DLG                    158
#define IDD_FILL_GRADIENT               159
#define IDD_FILL_PATTERN                160
#define IDD_DIALOG_ACTION               161
#define IDB_LINESTYLE                   162
#define IDC_ZOOMCURSOR1                 167
#define IDC_ZOOMCURSOR                  168
#define IDD_DIALOG_TEXT                 169
#define IDD_DIALOG_GROUP                171
#define IDD_DIALOG_NEW_DOC              172
#define IDD_INSERTCONTROL               173
#define IDR_TREE_POPUP                  174
#define IDD_DIALOG_WARN                 175
#define IDD_DIALOG_REAL_LINE            176
#define IDD_DIALOG_CONDUIT              178
#define IDD_DIALOG_LINK_VIEW            179
#define IDD_DIALOG_BUTTON               180
#define IDD_DIALOG_SET_ACTION           182
#define IDD_DIALOG_SET_LINE_ACTION      183
#define IDD_DIALOG_SET_FILL_ACTION      184
#define IDD_DIALOG_SET_RAY_ACTION       185
#define IDD_DIALOG_SET_PERCENT_ACTION   187
#define IDD_DIALOG_SET_MOVE_ACTION      189
#define IDD_DIALOG_SET_ROUTE_ACTION     190
#define IDD_DIALOG_SET_SIZE_ACTION      192
#define IDD_DIALOG_SET_SIZEW_ACTION     193
#define IDD_DIALOG_CAR                  196
#define IDD_DIALOG_ROTARY               197
#define IDC_APPNAME                     1004
#define IDC_AUTHOR                      1005
#define IDC_KEYWORDS                    1006
#define IDC_COMMENTS                    1007
#define IDC_TITLE                       1008
#define IDC_SUBJECT                     1009
#define IDC_TEMPLATE                    1010
#define IDC_SAVEDBY                     1011
#define IDC_REVNUM                      1012
#define IDC_EDITTIME                    1013
#define IDC_LASTPRINT                   1014
#define IDC_CREATEDATE                  1015
#define IDC_LASTSAVE                    1016
#define IDC_NUMPAGES                    1017
#define IDC_NUMWORDS                    1018
#define IDC_NUMCHARS                    1019
#define IDC_SECURITY                    1020
#define IDC_FILL_COLOR                  1021
#define IDC_EDIT_TRANS                  1024
#define IDC_SPIN_TRANS                  1025
#define IDC_LINE_SIZE                   1027
#define IDC_SPIN_LINESIZE               1028
#define IDC_ARROW_START_SIZE            1029
#define IDC_LINE_COLOR                  1031
#define IDC_TAB1                        1033
#define IDC_SPIN_START_SIZE             1033
#define IDC_BUTTON_ONE_COLOR            1036
#define IDC_ARROW_END_SIZE              1037
#define IDC_BUTTON2                     1037
#define IDC_SPIN_END_SIZE               1038
#define IDC_RADIO_SHUIPING              1047
#define IDC_BUTTON_FORWD_COLOR          1048
#define IDC_RADIO_CHUIZHI               1048
#define IDC_NoFill                      1049
#define IDC_BUTTON_BACK_COLOR           1049
#define IDC_RADIO_DUIJIAO_UP            1049
#define IDC_COMBO_LINESTYLE             1050
#define IDC_RADIO_RIGHT_UP              1050
#define IDC_RADIO7                      1051
#define IDC_RADIO8                      1052
#define IDC_BUTTON_WELL                 1053
#define IDC_RADIO9                      1053
#define IDC_BUTTON_TWO_COLOR            1054
#define IDC_BUTTON_SAMPLE               1055
#define IDC_RADIO10                     1056
#define IDC_RADIO11                     1057
#define IDC_RADIO12                     1058
#define IDC_RADIO13                     1059
#define IDC_RADIO14                     1060
#define IDC_RADIO1                      1061
#define IDC_RADIO2                      1062
#define IDC_RADIO3                      1063
#define IDC_RADIO4                      1064
#define IDC_RADIO_SHUIPING2             1065
#define IDC_EDIT1                       1065
#define IDC_EDIT_POINTNO                1065
#define IDC_EDIT_LINK_VIEW              1065
#define IDC_EDIT_POINT_NO               1065
#define IDC_RADIO_CHUIZHI2              1066
#define IDC_EDIT_X_MAX                  1066
#define IDC_EDIT_MIN                    1066
#define IDC_RADIO_DUIJIAO_UP2           1067
#define IDC_COMBO_ACTION                1067
#define IDC_EDIT2                       1067
#define IDC_EDIT_COL_COUNT              1067
#define IDC_EDIT_Y_MIN                  1067
#define IDC_EDIT_CONDUIT_TRANS          1067
#define IDC_EDIT_MAX_PERCENT            1067
#define IDC_EDIT_MIN_ANGLE_VALUE        1067
#define IDC_EDIT_SPEED                  1067
#define IDC_RADIO_RIGHT_UP2             1068
#define IDC_COMBO_RAGE                  1068
#define IDC_EDIT5                       1068
#define IDC_EDIT_GROUP_ID               1068
#define IDC_EDIT_DATE                   1068
#define IDC_EDIT_Y_MAX                  1068
#define IDC_COMBO_SPEED                 1068
#define IDC_EDIT_MIN_PERCENT            1068
#define IDC_EDIT_MAX_ANGLE_VALUE        1068
#define IDC_CHECK_ACTION                1069
#define IDC_EDIT_MIN_PIX                1069
#define IDC_EDIT_MIN_ANGLE              1069
#define IDC_EDIT_TEXT                   1070
#define IDC_EDIT_POINT3                 1070
#define IDC_EDIT_MAX_PIX                1070
#define IDC_EDIT_MAX_ANGLE              1070
#define IDC_EDIT_POINT4                 1071
#define IDC_COMBO_BORDER                1074
#define IDC_COMBO_FONT                  1077
#define IDC_EDIT_FONTSIZE               1078
#define IDC_SPIN_SIZE                   1079
#define IDC_COMBO_STYLE                 1080
#define IDC_COMBO_POSITION              1083
#define IDC_TEXTCOLOR                   1085
#define IDC_SPIN4                       1091
#define IDC_CHECK1                      1092
#define IDC_CHECK_PERCENT               1092
#define IDC_CHECK_POINT_VALUE           1092
#define IDC_CHECK_TEST                  1092
#define IDC_CHECK_LINE                  1092
#define IDC_CHECK_SHOW_MOVE             1092
#define IDC_CHECK_CONTRAROTATE          1092
#define IDC_CHECK_HIDE                  1092
#define IDC_CHECK_PERCENT_H             1093
#define IDC_CHECK_POINT_VALUE2          1093
#define IDC_CHECK_FILL                  1094
#define IDC_EDIT3                       1095
#define IDC_EDIT_MAX                    1095
#define IDC_EDIT_DOT_TRANS              1095
#define IDC_EDIT_START                  1095
#define IDC_CHECK_PERCENT_V             1095
#define IDC_SPIN5                       1096
#define IDC_SPIN_HEITH                  1096
#define IDC_SPIN_POINT_PERCENT          1096
#define IDC_CHECK_RAY                   1096
#define IDC_EDIT4                       1097
#define IDC_EDIT_PERCENT                1097
#define IDC_EDIT_POINT                  1097
#define IDC_EDIT_END                    1097
#define IDC_CHECK_MOVE_H                1097
#define IDC_EDIT_MIN_VALUE              1097
#define IDC_SPIN6                       1098
#define IDC_SPIN_PERCENT                1098
#define IDC_SPIN_DATE                   1098
#define IDC_CHECK_SIZE_HEIGHT           1098
#define IDC_BACK_COLOR                  1099
#define IDC_EDIT_TIME                   1099
#define IDC_CHECK_MOVE_V                1099
#define IDC_SPIN_HEIGHT                 1100
#define IDC_EDIT_WARN                   1100
#define IDC_CHECK_SIZE_WIDTH            1100
#define IDC_CHECK_ROUTE                 1101
#define IDC_EDIT_HEIGHT                 1102
#define IDC_CHECK_AUTOSIZE              1104
#define IDC_EDIT_NAME                   1105
#define IDC_SPIN_WIDTH                  1108
#define IDC_EDIT_WIDTH                  1109
#define IDC_CONTROLS                    1110
#define IDC_IGNOREREQUIREDCATEGORIES    1111
#define IDC_REQUIREDCATEGORIES          1112
#define IDC_IMPLEMENTEDCATEGORIES       1113
#define IDC_SERVERPATH                  1114
#define IDC_EDIT_GROUP_NAME             1115
#define IDC_STATIC_NORMAL               1116
#define IDC_SPIN_COL                    1118
#define IDC_BACKCOLOR                   1119
#define IDC_LINECOLOR                   1120
#define IDC_TITLECOLOR                  1121
#define IDC_SPIN_TIME                   1124
#define IDC_SPIN_TEXT                   1125
#define IDC_SPIN_WARN                   1126
#define IDC_BUTTON_BACKCOLOR            1128
#define IDC_BUTTON_COLOR_LINE1          1129
#define IDC_BUTTON_COLOR_LINE3          1131
#define IDC_BUTTON_COLOR_LINE5          1133
#define IDC_BUTTON_COLOR_LINE7          1135
#define IDC_EDIT_X_MIN                  1137
#define IDC_EDIT_POINT1                 1138
#define IDC_EDIT_POINT2                 1139
#define IDC_COMBO_FANGXIANG             1140
#define IDC_EDIT_TIMESPAN               1140
#define IDC_BUTTON_CONDUIT_COLOR        1141
#define IDC_BUTTON_DOT_COLOR            1142
#define IDC_BUTTON_TRUE_COLOR           1143
#define IDC_BUTTON_ERROR_COLOR          1144
#define IDC_IN_RANGE_COLOR              1145
#define IDC_COMM_ERROR_COLOR            1146
#define IDC_OUT_RANGGE_COLOR            1147
#define IDC_BUTTON_FALSE_COLOR          1148
#define IDC_COMBO_VIEW                  1149
#define IDC_BUTTON_LINE                 1150
#define IDC_BUTTON_PERCENT_H            1151
#define IDC_BUTTON_IN_COLOR             1151
#define IDC_BUTTON_FILL                 1152
#define IDC_BUTTON_OUT_COLOR            1152
#define IDC_IN_COLOR                    1152
#define IDC_BUTTON_PERCENT_V            1153
#define IDC_OUT_COLOR                   1153
#define IDC_COMBO_RAY_SPEED             1153
#define IDC_BUTTON_CommError_COLOR      1153
#define IDC_BUTTON_RAY                  1154
#define IDC_IN_START_COLOR              1154
#define IDC_COMBO_RAY_TYPE              1154
#define IDC_BUTTON_MOVE_H               1155
#define IDC_OUT_START_COLOR             1155
#define IDC_START_COLOR                 1155
#define IDC_BUTTON_SIZE_HEIGHT          1156
#define IDC_IN_END_COLOR                1156
#define IDC_END_COLOR                   1156
#define IDC_BUTTON_MOVE_V               1157
#define IDC_OUT_END_COLOR               1157
#define IDC_BUTTON_SIZE_WIDTH           1158
#define IDC_COMBO_REFERENCEPOINT        1158
#define IDC_BUTTON_ROUTE                1159
#define IDC_EDIT_MAX_VALUE              1159
#define IDC_COMBO_ROUTE_CENTER          1160
#define IDC_COMBO_CENTER                1161
#define IDC_EDIT_PIC_PATH               1164
#define IDC_PIC_PATH                    1165
#define IDC_FORWARD_COLOR               1168
#define IDC_BUTTON_PATH                 1168
#define ID_UNIT_SAVE                    8800
#define ID_CANCEL_EDIT_CNTR             32768
#define ID_CANCEL_EDIT_SRVR             32769
#define ID_INDICATOR_LOGO               32772
#define ID_FILE_SUMMARYINFO             32773
#define ID_TOOLBOXARROW                 32774
#define ID_TOOLBOXTEXT                  32775
#define ID_TOOLBOXLINE                  32776
#define ID_TOOLBOXCROSS                 32778
#define ID_TOOLBOX_BEELINE              32778
#define ID_TOOLBOXSOLIDRECT             32779
#define ID_TOOLBOXSOLIDROUNDRECT        32780
#define ID_TOOLBOXSOLIDOVAL             32781
#define ID_TOOLBOXSOLIDPOLYGON          32782
#define ID_TOOLBOXCHORD                 32783
#define ID_TOOLBOXPIE                   32784
#define ID_BUTTON32785                  32785
#define ID_TOOLBOXRECTANGLE             32785
#define ID_BUTTON32786                  32786
#define ID_TOOLBOX_ROUNDRECT_NOFILL     32786
#define ID_TOOLBOXOVAL                  32787
#define ID_TOOLBOXPOLYGON               32788
#define ID_TOOLBOXPIPE                  32789
#define ID_TOOLBOX_CONDUIT              32789
#define ID_TOOLBOXBUTTON                32790
#define ID_TOOLBOXBITMAP                32791
#define ID_TOOLBOXSUBBITMAP             32792
#define ID_TOOLBOXGROUP                 32793
#define ID_TOOLBOX_GROUP                32793
#define ID_TOOLBOXDEGROUP               32794
#define ID_TOOLBOX_DEGROUP              32794
#define ID_TOOLBOXCELL                  32795
#define ID_TOOLBOXDECELL                32796
#define ID_TOOLBOX_DECELL               32796
#define ID_TOOLBOXRTCURVE               32797
#define ID_TOOLBOX_TIME_CURVE           32797
#define ID_TOOLBOXSTROKE                32798
#define ID_TOOLBOXWARN                  32799
#define ID_TOOLBOXREPORT                32800
#define ID_TOOLBOXOVERSEE               32801
#define ID_TOOLBOXXY                    32802
#define ID_TOOLBOXTEMPLE                32803
#define ID_VIEW_PAPERCOLOR              32804
#define ID_OBJECT_LINECOLOR             32805
#define ID_OBJECT_FILLCOLOR             32806
#define ID_FORMATTING_FONT              32807
#define ID_FORMATTING_SIZE              32808
#define ID_FORMATTING_COLOR             32809
#define ID_FORMATTING_BOLD              32810
#define ID_FORMATTING_ITALIC            32811
#define ID_FORMATTING_UNDERLINE         32812
#define ID_FORMATTING_LINE_COLOR        32814
#define ID_FORMATTING_BACK_COLOR        32815
#define ID_OBJECT_MOVETOFRONT           32816
#define ID_OBJECT_MOVETOBACK            32817
#define ID_OBJECT_MOVEFORWARD           32818
#define ID_OBJECT_MOVEBACK              32819
#define ID_LINE_WIDTH                   32820
#define ID_LINE_STYPE                   32821
#define ID_LEFTARROW_STYLE              32822
#define ID_RIGHTARROW_STYLE             32823
#define ID_DRAW_CURVE                   32851
#define ID_LINE_WIDTH_2                 32853
#define ID_VIEW_FORMAT                  32854
#define ID_VIEW_WORKSPACE               32855
#define ID_VIEW_TOOLBOX                 32856
#define ID_VIEW_GRID                    32857
#define ID_VIEW_SHOWOBJECTS             32858
#define ID_INSERT_FILE                  32859
#define ID_INSERT_CHART                 32860
#define ID_INSERT_OLE_FILE              32861
#define ID_SETTING_PAGE_COLOR           32862
#define ID_TEST                         32864
#define ID_DRAW_SELECT                  32865
#define ID_EDIT_PROPERTIES              32870
#define ID_SETTING_PAGE_SIZE            32872
#define ID_TOOLBOX_ARROW                32873
#define ID_OBJECT_LOADSUB               32876
#define ID_ALIGN_LEFT                   32877
#define ID_ALIGN_RIGHT                  32878
#define ID_ALIGN_TOP                    32879
#define ID_ALIGN_BOTTOM                 32880
#define ID_ALIGN_LEFTRIGHT              32881
#define ID_ALIGN_TOPBOTTOM              32882
#define ID_ALIGN_CENTER                 32883
#define ID_ALIGN_HORZ                   32884
#define ID_ALIGN_VERT                   32885
#define ID_ROTATE                       32886
#define ID_ALIGN_SAME                   32887
#define ID_ALIGN_SAME_LEFTRIGHT         32889
#define ID_ALIGN_SAME_TOPBOTTOM         32890
#define ID_INSERT_ACTIVEX               32891
#define ID_PUPOP_ACTIVE                 32892
#define ID_POPUP_CLOSE                  32893
#define ID_POPUP_PROPERTY               32894
#define ID_POPUP_VIEW_PROPERTY          32895
#define ID_POPUP_MIN                    32896
#define ID_TOOLBOX_QIE                  32900
#define ID_PUPUP_LOCK                   32901
#define ID_POPUP_PROPERTIES             32902
#define ID_POPUP_ACTION                 32903
#define ID_POPUP_CAR                    32904
#define ID_INSERT_CAR                   32905
#define ID_INSERT_ROTARY                32906
#define ID_MOUSPOINT                    59143
#define ID_MOUSCAPTION                  59144
#define IDW_TABDOCKBAR                  59502

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        198
#define _APS_NEXT_COMMAND_VALUE         32907
#define _APS_NEXT_CONTROL_VALUE         1176
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
